### ISSUE TITLE
Screenshot Confusion

### ISSUE THREAD

**Issue by CallieCoder** [learn-co-curriculum/interpolation-readme#23]
It would be helpful and more instructive if the screenshots visually depicted the Sandbox and IDE visuals. Specifically, some of the screenshots for irb coding have numbered lines, whereas the Sandbox and IDE interface for the terminal/irb section is NOT numbered. This initially causes visual confusion because the screenshot looks like file coding (which has numbered lines), when its supposed to go into the unnumbered terminal section. As a newbie, its just very confusing to look at and inconsistent with the written instructions. (Matching the screen colors to black would also be helpful, but less important.)

**Comment by cjbrock** [comment]
Thanks @CallieCoder! As we update the curriculum going forward, we will take that into consideration and will absolutely make sure to have screenshots match the IDE. 

// <3 Corinna
